name: Python Package
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          sudo apt install libsasl2-dev python3-dev libldap2-dev libssl-dev upx
      - name: Build
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry install --no-dev
          poetry build
      - name: publish to pypi
        if: startsWith(github.ref, 'refs/tags/')
        run: poetry publish
  pyinstaller:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
          - ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          sudo apt install libsasl2-dev libldap2-dev libssl-dev upx
      - if: ${{ matrix.os == 'ubuntu-18.04' }}
        run: sudo apt install python3-dev
      - name: Compile binary
        run: ./pyinstaller.sh
      - name: Upload binaries to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/openvpn-ldap-auth
          asset_name: openvpn-ldap-auth-${{ env.RELEASE_VERSION }}-${{ matrix.os }}-amd64
          tag: ${{ github.ref }}
  debian_package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
          - ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
          cat /etc/os-release | grep UBUNTU_CODENAME >> $GITHUB_ENV
      - name: Generate DEB package
        run: |
          sudo apt install python3-pip ruby-rubygems
          sudo gem install fpm
          fpm -s python -t deb --python-bin=python3 openvpn-ldap-auth==${{ env.RELEASE_VERSION }}
      - name: Test DEB package
        run: sudo apt install ./python-openvpn-ldap-auth_${{ env.RELEASE_VERSION }}_all.deb
      - name: Upload DEB package to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: deb_dist/python3-openvpn-ldap-auth_${{ env.RELEASE_VERSION }}-1_all.deb
          asset_name: python3-openvpn-ldap-auth_${{ env.RELEASE_VERSION }}-1${{ env.UBUNTU_CODENAME }}_all.deb
          tag: ${{ github.ref }}
