name: Python Package
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
  pyinstaller:
    runs-on: ${{ matrix.os }}
    matrix:
      os: [ ubuntu-20.04, ubuntu-18.04, ubuntu-16.04 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Compile binary
        run: ./pyinstaller.sh
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/openvpn-ldap-auth
          asset_name: openvpn-ldap-auth-${{ matrix.os }}-amd64
          tag: ${{ github.ref }}
